version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest'
    working_directory: ~/repo

    environment:
      # Customize th eJVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencis-{{ checksum "pom.xml"}}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          mvn dependency: go-offline
      - save_cache:
          paths: ~/.m2
          key:  v1-dependencis-{{ checksum "pom.xml"}}
       # run tests
      - run : mvn integration-test